supabase/supabase-py

.gitignore, supabase_py/client.py, supabase_py/request_builder.py
=> wrap postgres py

tests/conftest.py, tests/test_client.py, tests/test_dummy.py
The test suite has some minor setup duplication at the top of each function. Namely,
```python
url: str = os.environ.get("SUPABASE_TEST_URL")
key: str = os.environ.get("SUPABASE_TEST_KEY")
supabase: Client = create_client(url, key)
```
This change factors that test setup into a pytest fixture that is created once and shared across the tests that require a `supabase.Client`.
=> Reduce test code duplication via supabase Client in pytest fixture

.github/workflows/pre-commit_hooks.yaml, .pre-commit-config.yaml, README.md, pyproject.toml, supabase_py/__init__.py, supabase_py/client.py, supabase_py/lib/__init__.py, supabase_py/lib/query_builder.py, tests/test_client.py, tests/test_dummy.py
Enforces code consistency via pre-commit hooks and checks pushed code on all branches in CI
I left off the mypy check for now because there were some tricky type errors in the query builder 
Resolves #26
=> Add pre-commit hooks enforcing a standard style

.github/workflows/pre-commit_hooks.yaml, supabase_py/client.py, supabase_py/lib/storage/storage_bucket_api.py, tests/test_client.py, tests/test_dummy.py
Formats  all previously unformatted files using the pre-commit hook in #28 so that we can have a passing build
None
Checks start on PR, files formatted
=> Format unformatted files

supabase_py/lib/query_builder.py
Fixes https://github.com/supabase/postgrest-py/issues/7 and #30 
Why are we monkey patching postgrest-py here? If we really need to hide the async reality and offer a synchronous interface, can we move it down to the postgrest-py layer so at least it's tested and kept in sync?
=> fix: missing json bodies in patch and put requests

supabase/lib/query_builder.py
Context: 
The current monkey-patched query builder does not return rows from the query instead returning an empty string. This is because [postgREST only returns the response when the header `Prefer: return=representation` is included](https://postgrest.org/en/v7.0.0/api.html#deletions). We have introduced this header as a default
Fix #22
=> Add header to query builder

supabase/client.py
In line 101, method `from_` returns a Postgrest-py RequestBuilder, not a SupabaseQueryBuilder
=> Remove wrong return type hinting

README.md
using the right badge "supabase" instad of "supabase-py"
=> fixing pypi badge in readme

pyproject.toml, supabase/lib/auth_client.py, supabase/lib/query_builder.py, supabase/lib/storage/storage_file_api.py, tests/test_client.py
=> feat: unify http client to be httpx

supabase/client.py, supabase/lib/client_options.py, supabase/lib/constants.py, supabase/lib/storage_client.py, test.ps1, tests/conftest.py, tests/test_client_options.py
Closes #50 
This PR: 
- Adds more type hints throughout.
- Adds typed supabase `Client` options in the form of `ClientOptions`.
- Adds a `test.ps1` file that is equivalent to `test.sh`, to more easily run tests on Windows.
=> Add typed client options

poetry.lock, pyproject.toml, supabase/client.py, supabase/lib/auth_client.py, supabase/lib/client_options.py, supabase/lib/constants.py, tests/test_client.py, tests/test_client_options.py
Now client options class does not make a deep copy in  the replace method because local storage is an abstract class and not dict like before
=> fix: update gotrue version and modify client options class

supabase/__init__.py, supabase/lib/__init__.py, supabase/lib/storage/__init__.py, supabase/lib/storage/storage_bucket_api.py, test.ps1, tests/test_storage.py
In the last PR we introduced some changes to the tests. One of them was a cleanup function that double-checked all test buckets were deleted after the tests run, since the empty and delete methods of the bucket fixture don't run if the test that created the bucket fails.
Nevertheless, tests were still failing because of two reasons:
1. The cleanup function called list_buckets before the buckets were deleted, so sometimes we face a 404 response, which we have to avoid since that means the bucket has already been deleted.
2. Since we were deleting buckets based on the prefix of their id, when multiple test runs are happening at the same time and one finishes before another one, it would delete all test buckets and tests would fail in the runs that were still going .
The solution to 1) is an …
=> tests: ignore 404 when double-checking bucket deletion

supabase/client.py
Fixes #217
The code was modified to pass options.schema to the _init_postgrest_client function through a new schema parameter to in turn pass the schema information to the SyncPostgrestClient constructor.
=> fix: pass schema to postgrest initialization 

supabase/client.py, supabase/lib/client_options.py
Apologies if I'm doing something wrong - this is my first open source contribution. I'm running two tests to help pass checks for PR/234. This is the PR in question: https://github.com/supabase-community/supabase-py/pull/234
=> Continuation of Pr/234: ran isort and black for tests

poetry.lock
- Dataclasses is no longer needed. It is a dependency needed only for Python < 3.7. Realtime, however requires Python >= 3.7, and so this dep isn't needed.
- Fixes https://github.com/supabase-community/supabase-py/issues/33#issuecomment-1399638278 This issue comes up when using this library in AWS Lambda with serverless framework plugin serverless-python-requirements and this lock file makes it hard to deploy to Lambda with environments Python >= 3.7.
- Already removed in realtime https://github.com/supabase-community/realtime-py/pull/48
=> Update poetry.lock; Remove dataclasses dependency

supabase/client.py, tests/test_function_configuration.py
See #447 for context
Closes #463 , #418 , #447
=> fix: use correct functions url

.github/workflows/ci.yml, supabase/client.py, supabase/lib/auth_client.py, tests/test_client_options.py
Fixed some types and also refactored the client options test by creating a class to make it more readable.
=> chore: fixed some types

README.md
=> Add Storage Examples

.github/workflows/ci.yml, MAINTAINERS.md
- Supabase-py uses `develop` as the default branch. Therefore we should release from `develop` and not `main`
- Also adds `olirice` as maintainer
=> fix: change release branch to develop

supabase/client.py
This will now allow the correct auth headers for a authenticated user to be passed over to the postgrest client. In this setup the postgrest and storage client are lazy initialised and each time a event triggers that could cause an auth token to update we reset the private variable holding the postgrest and storage clients.
No complying with the RLS policies without handling it in your code yourself
Automatic handling of complying with the RLS polices with postgrest and storage.
Fixes #185
=> Fix issue of RLS not working with Postgrest and Storage

.pre-commit-config.yaml
Remove markdown files from the pre-commit line endings check
This check is breaking the CI pipeline when we do a release
The CI pipeline should no longer be affected by this check
=> Ignore line endings of markdown files

README.md, pyproject.toml
=> fix: correct semantic release variable names

.github/workflows/ci.yml, supabase/client.py
Narrow the events we listen to in order to reset the postgrest and storage libraries
We are listening to every event
We are only listening to a select few who might trigger a JWT refresh
=> feat: narrow the auth event listening

supabase/lib/client_options.py
Looks like `fetch` was included in the ClientOptions because it must've been copied over from the JS client 😦
=> fix: remove fetch from clientoptions

supabase/client.py, tests/test_function_configuration.py
see title, to fully remove in v1.3.0. Address #576 
- need to update docs
=> feat: add functions property

README.md
Swap `delete` out, `remove` in the Storage section of the top-level readme.
Documentation update
Documentation is using a `delete` function to remove a file, but I was hitting an error when using it:
`AttributeError: 'SyncBucketProxy' object has no attribute 'delete'`
I'm pretty sure `remove` is the keyword that we need to use:
https://github.com/supabase-community/storage-py/blob/main/storage3/_sync/file_api.py#L277
n/a - no functionality changes just documentation
I'm brand new to supabase and really loving this project. Just hope this documentation update helps some other noob out down the line.
=> README / Storage -- Update `delete` file to `remove` file

pyproject.toml
Version bump to 0.3.1 of functions-py
=> chore: upgrade to the latest functions-py

supabase/client.py, supabase/lib/auth_client.py, supabase/lib/client_options.py
Add flow_type option to client options for gotrue-py
Only supports `implicit` auth flow
Can now select between `pkce` and `implicit` auth flow
=> fix: add flow_type to client options

README.md
Incomplete String in `### Download a file` (README.md)
Documentation update
The current code in the documentation has a missing quotation mark in the `download()` function.
The code in the documentation has been corrected to include the missing quotation mark in the `download()` function.
This PR fixes a typographical error in the code provided in the documentation.
=> add: complete string

poetry.lock, supabase/__init__.py, supabase/_async/client.py, supabase/_sync/client.py, supabase/client.py
Add a new create method to handle async token retrieval
The library isn't fully async and complains when trying to call `get_session` inside of `_get_token_header` from a `@property`.
The library should now be fully async as the `get_session` can be called async since we've moved the `_get_token_header` to the new `create` method instead of calling it from a `@property`.
=> feat: add create method to handle token headers

supabase/_async/client.py
Bug fix
`supabase.auth.sign_up` method [doesn't work](https://github.com/supabase-community/supabase-py/issues/654) when using `async`, it raises `TypeError`
```python
TypeError: object NoneType can't be used in 'await' expression
```
`supabase.auth.sign_up` method now works when using `async`
This is the same code as the issue #654:
```python
import os
import trio
from dotenv import load_dotenv
load_dotenv()
async def main():
from supabase._async.client import AsyncClient, create_client
DB_URL: str = os.getenv("DB_URL")
ANON_KEY: str = os.getenv("ANON_KEY")
supabase: AsyncClient = await create_client(DB_URL, ANON_KEY)  # works fine
email: str = "test@gmail.com"
password: str = "test123"
user = await supabase.auth.sign_up({"email": email, "password": password})
trio.run(main)
```
This is …
=> 🐛 fix #654: Add `AsyncMemoryStorage` to `AsyncClient` options

CONTRIBUTING.md, README.md
Docs update:
- Added more setup instructions and resources (linked) for Python, conda, and poetry
- Added links to mentioned community spaces (Discord, Discussions tab)
- Specified guidelines for filing issues and requests
- Gave instructions on linking issues/PRs
- Changed README structure to avoid repetition of added information
Missing potentially helpful information for new contributors.
Improved the onboarding experience for new contributors by including more relevant and helpful information/instructions, resources, and guidelines. 
N/A
=> docs (sunbase-py) updated setup instructions, PR guidelines, added resources & links

supabase/__init__.py
Bug fix for #682
Missing `ClientOptions` when importing from the `supabase` namespace
Adding `ClientOptions` to the `__init__.py` file
=> fix: add missing ClientOptions to the main init file

supabase/_async/client.py, supabase/_sync/client.py
Bug fix
This PR should be merged before https://github.com/supabase-community/postgrest-py/pull/372 in order for the version bump to happen correctly.
Returning wrong return type from `.rpc` method, also there is no default for `params` which means you have to pass an empty dict even if the function doesn't have any parameters.
Returning correct return type from `.rpc` method and now has `None` as default for `params` so you don't need to pass a dict if there are no parameters to the function.
In relation to #700 and https://github.com/supabase-community/postgrest-py/pull/372
=> fix: Update rpc return type

.github/workflows/ci.yml
CI shouldn't run if there is a dependency update to the CI itself
CI runs when there is a dependency update to the CI itself
=> ignore paths on ci

.pre-commit-config.yaml, poetry.lock, pyproject.toml
Removing mdformat-gfm as it had no real benefit to the project and is creating friction for the generated CHANGELOG.md
Changelog is failing in formatting tests as it doesn't follow github flavour md.
Changelog won't failing the formatting tests.
=> remove mdformat-gfm

supabase/_async/client.py, supabase/_sync/client.py
Bug fix
Currently leaking session data if you instantiate two clients in the same request.
No longer leaking session data.
Issue #762
=> fix: remove default mutable argument from client creation

supabase/_async/client.py, supabase/_sync/client.py, tests/test_client.py
Bug fix for #420 
Supports setting the client auth context for a particular user and therefore RLS.
- Updated both sync and async clients.
- Added unit tests.
If a client is created with an `Authorization` header provided in `ClientOptions`, it is overwritten with the supabase key.
For example:
```python
url = "https://example.supabase.com"
key = "apikey"
options = ClientOptions(headers={"Authorization": "Bearer userjwt"})
supabase = create_client(url, key, options)
```
The `Authorization` header provided via client options is used for requests.
```python
```
If no header is provided the supabase key is used.
This allows us to set the auth context in the same manner [described in the official Edge Function documentation](https://supabase.com/docs/guides/functions/auth#auth-context).
=> fix(user auth context): do not overwrite provided client options Authorization header

supabase/_async/client.py, supabase/_sync/client.py
Refactor changes discussed in #798
Right now, `acreate_client` is a re-import of the `_async.client.create_client` function. This function, in its body, calls the `AsyncClient.create` asynchronous class method (see [source code](https://github.com/supabase-community/supabase-py/blob/fee2b5e7ea013d06fb4e0dc6492ec053974fba10/supabase/_async/client.py#L96)). This method itself calls `AsyncClient.__init__` (see [source code](https://github.com/supabase-community/supabase-py/blob/fee2b5e7ea013d06fb4e0dc6492ec053974fba10/supabase/_async/client.py#L31)). This chain of function calls, passing the same arguments with the same names three times until it reaches the destination constructor, seems to introduce some unnecessary abstractions.
Both `_async.client.create_client` and …
=> Refactor create_client functions to call constructor directly

supabase/_async/client.py, supabase/_sync/client.py
Remove the existing schema property and add a schema method. The property wasn't being used anywhere in the code hence its removal.
You cannot set schema after instantiating client.
You can set schema using the `schema` method after instantiating the client.
=> feat: add schema method to the client

supabase/_async/client.py, supabase/_sync/client.py
- Add `verify`, see https://github.com/supabase-community/auth-py/pull/506 and https://github.com/supabase-community/auth-py/issues/320
- WIP.
=> Add verify

supabase/_async/client.py
The async create_client method is calling `AsyncClient.create` without awaiting it, leading to the return of a nested coroutine and falsifying the return type of `create_client`.
Users of `create_client` need to use a double `await` to use this function, which doesn't correspond to the indicated return type.
The method now correctly returns a coroutine that returns an `AsyncClient` on completion.
=> fix missing await in async create_client

supabase/_async/client.py, supabase/_sync/client.py, supabase/client.py
Fix https://github.com/supabase/supabase-py/issues/895
=> fix: remove old SupabaseRealtimeClient import

supabase/_async/auth_client.py, supabase/_async/client.py, supabase/_sync/auth_client.py, supabase/_sync/client.py
Add `verify` argument to `_init_supabase_auth_client()` for SSL certificate verification. This follows the convention set by `_init_postgrest_client()` and `_init_storage_client()`.
`verify` flag cannot be passed to the underlying `[Async]GoTrueClient`.
`_init_supabase_auth_client()` can be passed the `verify` flag that is propagated to the underlying `[Async]GoTrueClient`.
Follows convention of https://github.com/supabase/supabase-py/pull/813
=> fix: add `verify` argument to `_init_supabase_auth_client()`

tests/test_realtime.py
=> test: add realtime sync test

supabase/__init__.py
Bug fix to improve the use of the library.
Async client and errors aren't being exported from the `__init__.py` file.
Async client and errors are being exported from the `__init__.py` file.
=> fix: update exports from init file

Makefile, poetry.lock, pyproject.toml, supabase/_async/client.py, supabase/_sync/client.py, tests/_async/test_client.py, tests/test_client.py
=> fix: async set_auth for realtime in auth event listener

supabase/lib/client_options.py
Implicit flow type doesn't make sense when working with server side frameworks. This PR is to change the default `flow_type` to `pkce`
=> feat: set default flow_type to pkce

supabase/__init__.py, supabase/_async/client.py, supabase/_sync/client.py, supabase/client.py, supabase/lib/client_options.py, tests/test_client.py, tests/test_client_options.py
Bug fix for default values of async client options
closing #929
=> fix: async client options default values

poetry.lock, pyproject.toml, supabase/_async/client.py, supabase/_sync/client.py, supabase/lib/client_options.py, supabase/types.py
=> fix(realtime): enable auto_reconnect option from supabase client

poetry.lock, pyproject.toml
Bug fix
The `proxy` argument for `SyncGoTrueClient` was added in version 2.9.0 
As a result, having a lower version than 2.9.0 will cause an error
https://github.com/supabase/auth-py/releases/tag/v2.9.0
Currently having a lower version than `gotrue==2.9.0`, causes the following error: 
```
File "/opt/venv/lib/python3.11/site-packages/supabase/_sync/auth_client.py", line 33, in __init__
SyncGoTrueClient.__init__(
TypeError: SyncGoTrueClient.__init__() got an unexpected keyword argument 'proxy'
```
Related https://github.com/supabase/supabase-py/issues/949 but this issue is not fully resolved by raising the `httpx` version
Minimum version of `gotrue` updated to v2.9.0
Add any other context …
=> fix: raise the minimum version of gotrue to 2.9.0

README.md, poetry.lock, pyproject.toml, supabase/types.py
Related to #964 
This PR includes:
- **Refactoring**: Refactored `TypedDict` from `typing import TypedDict`
- **Docs Update**:  Updated description of python's version
=> fix: removed typing-extensions

supabase/_async/client.py, supabase/_sync/client.py
Currently, accessing data across multiple schemas using the `schema()` method incurs significant performance overhead due to the creation of a new PostgreSQL client for each call. This contrasts with directly querying tables, which leverages existing connections and avoids this repeated client instantiation. The overhead becomes particularly noticeable when working with numerous schemas, adding unnecessary milliseconds to query build time.
Thoughts?
=> fix: schema access optimization

poetry.lock, pyproject.toml
The last bump of httpx has been done in this commit: https://github.com/supabase/supabase-py/commit/fadbc4b41fc7ef2dc92929c28150901ea700f83f
httpx now release 0.28 (and 0.28.1) and this is causing some conflicts with other packages.
Unable to install supabase alongside some packages because of httpx
It should not change the existing install but not block project requiring httpx >= 0.28
=> chore: update httpx

Makefile, supabase/_async/auth_client.py, supabase/_sync/auth_client.py
Hi, my name is Pedro Manuel. I have modified the file to use super() instead of calling the base class constructor directly. This makes the code clearer and easier to maintain.
File update.
=> fix: update SupabaseAuthClient to use super instead of calling base class

supabase/_async/client.py, supabase/_sync/client.py
Bug fix
Schema method was being cached and calling the wrong schema each call
Schema method is no longer being cached and calls the correct schema each call
=> fix: schema method should use postgres method directly

supabase/_async/client.py, supabase/_sync/client.py
=> fix(postgrest): add missing count, head, and get params

supabase/_async/client.py, supabase/_sync/client.py
Deepcopy fails to copy thread objects, like I can't implement a config class that has a client instance of Supabase as a attribute
Bug fix for this issue: https://github.com/supabase/supabase-py/issues/1129
SyncClient.__init__ receives a `option` argument that could be a ClientOptions, this ClientOptions instance can also have specific implementations for storage.
Then, __init__ tries to copy  the options attribute to it's instance, since options.headers is a dictionary, a deepcopy garantees recursively that headers is copied too. But this drives to another kind's of unexpected erros since we don't have control of the implementation of any ClientOptions derived class.
The bug is:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
File …
```
=> fix: copy client options instead of deepcopy

poetry.lock, pyproject.toml
Bump version of realtime
Currently 2.5.x versions of realtime conflict with other libraries that use websockets library.
No new behaviour
Just bumping version, so that it does not conflict
=> feat(realtime): bump realtime from 2.4.3 to 2.5.1

README.md
This PR adds a documentation note to clarify that an explicit call to `client.auth.sign_out()` is required to ensure proper shutdown of the Supabase client.
Without this call, background WebSocket connections and threads may continue running, potentially leading to resource leaks and hanging processes.
Relates to: #926
=> docs: add note about explicit client.auth.sign_out() for proper shutdown (#926)

.pre-commit-config.yaml, poetry.lock, pyproject.toml, supabase/_async/client.py, supabase/_sync/client.py, tests/test_client_options.py, tests/test_realtime.py
Tooling update, replacing a bunch of dependencies with ruff which is faster and is quite compatible with the tools it replaces.
=> chore: replace isort, black, pyupgrade and autoflake with ruff

pyproject.toml, uv.lock
Removes `gotrue` and `supafunc` from dependencies as they're not longer needed.
Both packages are dependencies and unused.
No more unused packages.
=> fix: remove deprecated supafunc and gotrue

src/functions/README.md
This PR significantly improves the Functions-py README documentation by addressing several usability issues and providing comprehensive examples.
- Add multiple installation methods (pip, uv, poetry)
- Include comprehensive async and sync client examples  
- Add proper error handling and authentication examples
- Link to official Supabase Functions documentation
- Improve code structure and readability
Fixes #1216
Documentation update
The current README has minimal installation instructions (only pip3), lacks proper examples with error handling and authentication, and doesn't provide synchronous client examples. The documentation reference is vague without proper links.
The updated README provides:
- Multiple installation options for different package managers
- Complete, realistic …
=> docs(functions): improve README with installation options and examples

src/functions/Makefile, src/functions/pyproject.toml, src/functions/run-unasync.py, src/functions/src/supabase_functions/_async/functions_client.py, src/functions/src/supabase_functions/_sync/functions_client.py, src/functions/tests/test_errors.py
Make `mypy` work with `functions`, and add it to CI.
=> chore(functions): add mypy checks to functions

src/storage/Makefile, src/storage/pyproject.toml, src/storage/run-unasync.py, src/storage/src/storage3/_async/file_api.py, src/storage/src/storage3/_sync/file_api.py, src/storage/src/storage3/exceptions.py, src/storage/tests/_async/test_client.py, src/storage/tests/_sync/conftest.py, src/storage/tests/_sync/test_client.py, uv.lock
Fix type definitions in storage.
`mypy` throws errors in both `src/storage` and `tests`.
`mypy` passes for both. Also took the opportunity to improve `make` default message for `storage`.
=> feat(storage): mypy storage
