supabase_py/lib/realtime_client.py
=> [WIP]: Add transformers

README.md
This PR aims to help improve the documentation and contribute to fixing part of #11  
NIL
NIL
None for now, update if there are additional changes later.
fixes #11
=> Minor Updates to README

pyproject.toml, supabase_py/__init__.py
Misc version and author hotfix for new release
=> update version and add author

README.md, pyproject.toml, supabase_py/__init__.py
title and short diff explains it all really
=> Hotfix for version/author

supabase_py/client.py, supabase_py/lib/realtime_client.py, supabase_py/lib/storage/storage_bucket_api.py, supabase_py/lib/supabase_storage_client.py, tests/test_client.py, tests/test_dummy.py
I decided to split Storage API PR into Chunks. This is a first of a few and it introduces the Storage Bucket API
Will need to make storage bucket public in order to introduce storage bucket tests
=> Add Storage Bucket API

pyproject.toml
bumped postgrest-py to latest version (0.5.0)
=> bump postgrest-py to latest version (0.5.0)

pyproject.toml, supabase_py/__init__.py, supabase_py/client.py, supabase_py/lib/constants.py
Add some default headers to wrapped client libs.
See #42.
Some other minor changes included:
- Add Black as a dev dependency, because we use it in the pre-commit hook.
=> Add some default headers to wrapped client libs

CONTRIBUTING.md, supabase/lib/MAINTAINERS.md
As discussed in #99 
Adding information about the contribution process in a bit
=> Add maintainers file

supabase/lib/storage/storage_file_api.py
More info: https://github.com/encode/httpx/discussions/2004
=> fix: use httpx in storage file upload

supabase/__init__.py
To be merged after updating postgrest_py.
=> feat: export APIResponse and APIError from postgrest-py

README.md
=> Update README.md to new API

README.md
Adding `delete` example to ReadMe.
=> add deletion example to readme

README.md, poetry.lock, pyproject.toml
- Reverts supabase-community/supabase-py#222
- Fixes end of file at README.md
- Forces latest storage version
=> fix: downgrade python-semantic-release, fix end of file at README and force latest storage version

README.md
Feature
N/A
Available via conda natively
None
----
waiting on https://github.com/conda-forge/staged-recipes/pull/20886
=> add conda package instructions to readme

README.md
Installation, Usage etc. have been hidden
Fix #314, minimal update of Readme.md
See #314, parts of the readme are hidden as a comment. 
Installation and Usage etc. are now shown again.
=> docs: update readme to show hidden parts

supabase/client.py
timeout was not being passed through from constructor to postgrest
Fixes #293
=> fix: pass through timeout

poetry.lock, pyproject.toml
includes postgrest and storage update
=> chore: bump supabase version to 1.0.1

README.md
Minor fix in the readme to make the sample work
=> Fix sample for sign in with username + password

README.md
=> chore: add todos to README, potentially handoff

README.md
=> fix: incorrect example and document fault RLS

.github/CODEOWNERS, .github/workflows/ci.yml
=> chore: add CODEOWNERS

.github/workflows/ci.yml
Update the token variable to fix pypi deployment
Running into an error because the main branch is protected
The access token should bypass the branch protection
=> Add new token variable

README.md
=> Update README.md with completed tasks and rename to auth-py

supabase/_async/client.py, supabase/_sync/client.py
=> add correct token when a user is signed in

README.md, poetry.lock, pyproject.toml
=> chore: update to latest postgrest

.github/workflows/ci.yml
Just bumps the values as they were not even running:
=> Update action versions in CI/CD

.github/dependabot.yml
=> feat: add actions to dependabot

.github/CODEOWNERS
=> chore: update CODEOWNERS to use python-maintainers

.github/workflows/ci.yml
=> Ignore paths on push to CI

.github/workflows/ci.yml, .pre-commit-config.yaml
Update to latest autoflake and add Python 3.12 to the test suite
=> Add python 3.12 to the test suite

supabase/_async/client.py, supabase/_sync/client.py
Bug fix
User session is not always present when user is signed in
User session is always present when user is signed in
=> resolve user session inside of the create factory method

supabase/_async/client.py, supabase/_sync/client.py
- Initial Realtime integration.
=> Realtime integration

supabase/_async/client.py, supabase/_sync/client.py
Reverts supabase/supabase-py#878
=> Revert "Realtime integration"

poetry.lock
Fix https://github.com/supabase/supabase-py/issues/898
=> fix(realtime): update realtime for fixing NotConnectedError

supabase/lib/client_options.py
=> fix: storage type for async client options

poetry.lock, pyproject.toml
=> chore(deps): change version constraints on managed dependencies

supabase/__init__.py, tests/_async/test_client.py, tests/test_client.py, tests/test_client_options.py
=> chore(tests): increase coverage

README.md
=> chore: add open role to README.md

README.md
=> chore: remove hiring link from README.md
